- name: variables from file
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml  # Include the variables from vars.yaml file
  tasks: 
  - name: Display course information
    ansible.builtin.debug:
      msg: "Course: {{ Course }}, Trainer: {{ Trainer }}, Duration: {{ Duration }}"