- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER  # register the result of the command
    ignore_errors: true  # Ignore errors if the user does not exist

  - name: print user information
    ansible.builtin.debug:
      msg: "User info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #condition  # Check if the user does not exist (rc != 0)

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"